server:
  port: 8001

guns:
  file-upload-path: /app/webstack/images    #文件上传目录(不配置的话为java.io.tmpdir目录)

beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用

log:
  path: /applog/webstack/manage-logs

spring:
  datasource:
    url: jdbc:mysql://zero.brock.fun:3306/rains_webstack?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: brock
    password: Iccc2018
    filters: wall,mergeStat



