server:
  port: 8080

guns:
  file-upload-path: images

log:
  path: logs

spring:
  datasource:
    url: jdbc:mysql://zero.brock.fun:3306/prd_webstack?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: brock
    password: Iccc2018
    filters: wall,mergeStat



